// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/liquidity/add/[[...poolId]]": InferRoute<import("./src/pages/liquidity/add/[[...poolId]]").RouteType>;
    "/liquidity/create/[[...selectId]]": InferRoute<import("./src/pages/liquidity/create/[[...selectId]]").RouteType>;
    "/liquidity/position/[[...positionId]]": InferRoute<import("./src/pages/liquidity/position/[[...positionId]]").RouteType>;
    "/liquidity/select/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/[[...selectId]]").RouteType>;
    "/liquidity/select/pools/[[...selectId]]": InferRoute<import("./src/pages/liquidity/select/pools/[[...selectId]]").RouteType>;
  }

  interface StaticRouter {
    "/404": StaticRoute;
    "/451": StaticRoute;
    "/add/[[...currency]]": StaticRoute;
    "/bridge": StaticRoute;
    "/burn-dashboard": StaticRoute;
    "/buy-crypto": StaticRoute;
    "/cake-staking": StaticRoute;
    "/cake-staking/redeem": StaticRoute;
    "/competition/finished/[competition]": StaticRoute;
    "/competition/finished": StaticRoute;
    "/competition": StaticRoute;
    "/create-profile": StaticRoute;
    "/farms/history": StaticRoute;
    "/farms": StaticRoute;
    "/find": StaticRoute;
    "/gauges-voting": StaticRoute;
    "/home": StaticRoute;
    "/ido/[ido]": StaticRoute;
    "/ido": StaticRoute;
    "/ido/w3w": StaticRoute;
    "/ifo/history": StaticRoute;
    "/ifo": StaticRoute;
    "/increase/[[...currency]]": StaticRoute;
    "/": StaticRoute;
    "/info/[chainName]": StaticRoute;
    "/info/[chainName]/pairs/[address]": StaticRoute;
    "/info/[chainName]/pairs": StaticRoute;
    "/info/[chainName]/tokens/[address]": StaticRoute;
    "/info/[chainName]/tokens": StaticRoute;
    "/info": StaticRoute;
    "/info/infinity/[chainName]": StaticRoute;
    "/info/infinity/[chainName]/pairs": StaticRoute;
    "/info/infinity/[chainName]/tokens/[address]": StaticRoute;
    "/info/infinity/[chainName]/tokens": StaticRoute;
    "/info/infinity": StaticRoute;
    "/info/infinity/tokens/[address]": StaticRoute;
    "/info/infinity/tokens": StaticRoute;
    "/info/pairs/[address]": StaticRoute;
    "/info/pairs": StaticRoute;
    "/info/tokens/[address]": StaticRoute;
    "/info/tokens": StaticRoute;
    "/info/v3/[chainName]": StaticRoute;
    "/info/v3/[chainName]/pairs/[address]": StaticRoute;
    "/info/v3/[chainName]/pairs": StaticRoute;
    "/info/v3/[chainName]/tokens/[address]": StaticRoute;
    "/info/v3/[chainName]/tokens": StaticRoute;
    "/info/v3": StaticRoute;
    "/info/v3/pairs/[address]": StaticRoute;
    "/info/v3/pairs": StaticRoute;
    "/info/v3/tokens/[address]": StaticRoute;
    "/info/v3/tokens": StaticRoute;
    "/limit-orders": StaticRoute;
    "/liquid-staking/[contract]": StaticRoute;
    "/liquid-staking": StaticRoute;
    "/liquid-staking/request-withdraw/[contract]": StaticRoute;
    "/liquidity/[tokenId]": StaticRoute;
    "/liquidity": StaticRoute;
    "/liquidity/pool/[chainName]/[id]": StaticRoute;
    "/liquidity/pools": StaticRoute;
    "/liquidity/positions": StaticRoute;
    "/lottery": StaticRoute;
    "/mev": StaticRoute;
    "/migration/bcake": StaticRoute;
    "/migration": StaticRoute;
    "/nfts/activity": StaticRoute;
    "/nfts/collections/[collectionAddress]/[tokenId]": StaticRoute;
    "/nfts/collections/[collectionAddress]": StaticRoute;
    "/nfts/collections": StaticRoute;
    "/nfts": StaticRoute;
    "/pancake-squad": StaticRoute;
    "/pools/[chainName]/[id]": StaticRoute;
    "/pools/history": StaticRoute;
    "/pools": StaticRoute;
    "/position-managers/[[...slug]]": StaticRoute;
    "/pottery": StaticRoute;
    "/prediction": StaticRoute;
    "/prediction/leaderboard": StaticRoute;
    "/profile/[accountAddress]/achievements": StaticRoute;
    "/profile/[accountAddress]/activity": StaticRoute;
    "/profile/[accountAddress]": StaticRoute;
    "/profile": StaticRoute;
    "/profile/pancake-collectibles": StaticRoute;
    "/remove/[tokenId]": StaticRoute;
    "/simple-staking": StaticRoute;
    "/stable/[address]": StaticRoute;
    "/stable/add/[[...currency]]": StaticRoute;
    "/stable/remove/[[...currency]]": StaticRoute;
    "/swap": StaticRoute;
    "/swap/limit": StaticRoute;
    "/swap/twap": StaticRoute;
    "/teams/[id]": StaticRoute;
    "/teams": StaticRoute;
    "/terms-of-service": StaticRoute;
    "/trading-reward/cake-stakers": StaticRoute;
    "/trading-reward": StaticRoute;
    "/trading-reward/top-traders": StaticRoute;
    "/v2/add/[[...currency]]": StaticRoute;
    "/v2/migrate/[address]": StaticRoute;
    "/v2/pair/[[...currency]]": StaticRoute;
    "/v2/remove/[[...currency]]": StaticRoute;
    "/voting": StaticRoute;
    "/voting/proposal/[id]": StaticRoute;
    "/voting/proposal/create": StaticRoute;
  }
}
