packages:
  - 'packages/*'
  - 'packages/routing-sdk/**'
  - 'apps/*'
  - 'apis/*'
  - 'examples/*'
  - 'scripts'

catalog:
  viem: 2.31.3
  wagmi: ^2.14.11
  react: ^18.2.0
  react-dom: ^18.2.0
  next: 15.2.3
  '@vercel/functions': 2.0.0
  wrangler: 3.81.0
  '@aptos-labs/ts-sdk': 1.30.0
  '@types/react': ^18.2.21
  '@types/react-dom': ^18.0.6
  eslint: ^8.32.0
  '@next/eslint-plugin-next': 14.2.3
  jotai: ^2.4.3
  '@vanilla-extract/vite-plugin': ^4.0.2
